# -*- coding: utf-8 -*-
"""Sruthi Baskaran VAC

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11gGwLRLemHiUCH1LChohAFbhWc6Ss5Mv
"""

def bubbleSort(arr):
	n = len(arr)
	swapped = False
	for i in range(n-1):
		for j in range(0, n-i-1):

			if arr[j] > arr[j + 1]:
				swapped = True
				arr[j], arr[j + 1] = arr[j + 1], arr[j]
		
		if not swapped:
			return



arr = [99, 3, 25, 72, 22, 11, 60]

bubbleSort(arr)

print("Sorted array is:")
for i in range(len(arr)):
	print("% d" % arr[i], end=" ")